// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	filterMapIpBlocklist = "ip_blocklist"
	filterProgXdpFilter  = "xdp_filter"
)

// loadFilter returns the embedded CollectionSpec for filter.
func loadFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filter: %w", err)
	}

	return spec, err
}

// loadFilterObjects loads filter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filterObjects
//	*filterPrograms
//	*filterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilterObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterSpecs struct {
	filterProgramSpecs
	filterMapSpecs
	filterVariableSpecs
}

// filterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterProgramSpecs struct {
	XdpFilter *ebpf.ProgramSpec `ebpf:"xdp_filter"`
}

// filterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterMapSpecs struct {
	IpBlocklist *ebpf.MapSpec `ebpf:"ip_blocklist"`
}

// filterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterVariableSpecs struct {
}

// filterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterObjects struct {
	filterPrograms
	filterMaps
	filterVariables
}

func (o *filterObjects) Close() error {
	return _FilterClose(
		&o.filterPrograms,
		&o.filterMaps,
	)
}

// filterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterMaps struct {
	IpBlocklist *ebpf.Map `ebpf:"ip_blocklist"`
}

func (m *filterMaps) Close() error {
	return _FilterClose(
		m.IpBlocklist,
	)
}

// filterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterVariables struct {
}

// filterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterPrograms struct {
	XdpFilter *ebpf.Program `ebpf:"xdp_filter"`
}

func (p *filterPrograms) Close() error {
	return _FilterClose(
		p.XdpFilter,
	)
}

func _FilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filter_bpfel.o
var _FilterBytes []byte
