package mqtt_test

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"net"
	"testing"
	"time"

	"github.com/eclipse/paho.golang/paho"
	mqtt "github.com/mochi-mqtt/server/v2"
	"github.com/mochi-mqtt/server/v2/hooks/auth"
	"github.com/mochi-mqtt/server/v2/listeners"
	"github.com/stretchr/testify/require"

	"github.com/mochi-mqtt/server/v2/modules/routing"
	tlsprofiles "github.com/mochi-mqtt/server/v2/modules/security"
)

func TestFullIntegrationWithPaho(t *testing.T) {
	// 1. Setup Broker
	server := mqtt.New(nil)
	_ = server.AddHook(new(auth.AllowHook), nil)

	// Add Wildcard Tokens
	wildcardCfg := &tlsprofiles.WildcardTokensConfig{
		SharedSecret: []byte("test-secret"),
		Permissions: map[string][]string{
			"subscriber": {"devices/+/data"},
		},
	}
	err := server.AddHook(new(tlsprofiles.WildcardTokenHook), wildcardCfg)
	require.NoError(t, err)

	// Add Message Integrity FIRST so it validates before queuing
	integrityCfg := &tlsprofiles.MessageIntegrityConfig{
		RequireSignature: true,
		VerifySignature:  true,
		SharedSecret:     []byte("integrity-secret"),
	}
	err = server.AddHook(new(tlsprofiles.MessageIntegrityHook), integrityCfg)
	require.NoError(t, err)

	// Add Priority Messaging
	err = server.AddHook(new(routing.PriorityMessagingHook), &routing.PriorityMessagingConfig{
		AgingThresholdHigh:   100 * time.Millisecond,
		AgingThresholdNormal: 200 * time.Millisecond,
		SchedulerInterval:    10 * time.Millisecond,
	})
	require.NoError(t, err)

	// Start server on random port
	tcp := listeners.NewTCP(listeners.Config{ID: "t1", Address: "127.0.0.1:0"})
	err = server.AddListener(tcp)
	require.NoError(t, err)
	err = server.Serve()
	require.NoError(t, err)
	defer server.Close()

	time.Sleep(100 * time.Millisecond)

	// 2. Connect Subscriber Client
	connSub, err := net.Dial("tcp", tcp.Address())
	require.NoError(t, err)
	defer connSub.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// Collect received messages
	receivedMessages := make(chan string, 10)

	subClient := paho.NewClient(paho.ClientConfig{
		Conn: connSub,
		Router: paho.NewSingleHandlerRouter(func(p *paho.Publish) {
			receivedMessages <- string(p.Payload)
		}),
	})

	cack, err := subClient.Connect(ctx, &paho.Connect{
		ClientID: "subscriber",
		CleanStart: true,
		KeepAlive:  30,
	})
	require.NoError(t, err)
	require.Equal(t, byte(0), cack.ReasonCode)

	var token string
	for _, p := range cack.Properties.User {
		if p.Key == "wildcard-token" {
			token = p.Value
		}
	}
	require.NotEmpty(t, token, "expected wildcard token to be generated by broker")



	// Subscribe using wildcard token
	sack, err := subClient.Subscribe(ctx, &paho.Subscribe{
		Subscriptions: []paho.SubscribeOptions{
			{Topic: "devices/+/data", QoS: 0},
		},
		Properties: &paho.SubscribeProperties{
			User: []paho.UserProperty{{Key: "wildcard-token", Value: token}},
		},
	})
	require.NoError(t, err)
	require.Equal(t, byte(0), sack.Reasons[0])

	// 3. Connect Publisher Client
	connPub, err := net.Dial("tcp", tcp.Address())
	require.NoError(t, err)
	defer connPub.Close()

	pubClient := paho.NewClient(paho.ClientConfig{
		Conn: connPub,
	})

	_, err = pubClient.Connect(ctx, &paho.Connect{
		ClientID: "publisher",
		CleanStart: true,
	})
	require.NoError(t, err)

	publishMessage := func(payload, priority string, validSig bool) error {
		topic := "devices/sensor1/data"
		payloadBytes := []byte(payload)
		
		mac := hmac.New(sha256.New, []byte("integrity-secret"))
		mac.Write([]byte(topic))
		mac.Write(payloadBytes)
		sig := base64.StdEncoding.EncodeToString(mac.Sum(nil))
		if !validSig {
			sig = "badsig"
		}

		_, err := pubClient.Publish(ctx, &paho.Publish{
			Topic:   topic,
			Payload: payloadBytes,
			QoS:     0,
			Properties: &paho.PublishProperties{
				User: []paho.UserProperty{
					{Key: "integrity-signature", Value: sig},
					{Key: "priority", Value: priority},
				},
			},
		})
		return err
	}

	// Publish invalid signature (will be rejected and connection might be dropped depending on broker policy, 
	// but Mochi-MQTT usually just rejects the packet). 
	// Actually, wait: a QoS 0 publish doesn't return an ACK. The broker just drops it silently.
	_ = publishMessage("invalid-msg", routing.PriorityNormal, false)

	// Publish normal, high, urgent
	err = publishMessage("normal-msg", routing.PriorityNormal, true)
	require.NoError(t, err)
	err = publishMessage("high-msg", routing.PriorityHigh, true)
	require.NoError(t, err)
	err = publishMessage("urgent-msg", routing.PriorityUrgent, true)
	require.NoError(t, err)

	// 4. Verify received messages
	// We expect 3 messages in order: urgent, high, normal
	var received []string
	for i := 0; i < 3; i++ {
		select {
		case msg := <-receivedMessages:
			received = append(received, msg)
		case <-time.After(2 * time.Second):
			t.Fatal("timed out waiting for messages")
		}
	}

	require.Equal(t, 3, len(received))
	require.Equal(t, "urgent-msg", received[0], "urgent should arrive first")
	require.Equal(t, "high-msg", received[1], "high should arrive second")
	require.Equal(t, "normal-msg", received[2], "normal should arrive last")
}
